CC = gcc
LD = gcc

CFLAGS=-I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -std=c11
CFLAGS+=-D_POSIX_C_SOURCE=200809L -D_DEFAULT_SOURCE

LDFLAGS=-lglib-2.0

all: ssd1306_demo

ssd1306_demo: ssd1306_demo.o ssd1306.o
	$(LD) $(LDFLAGS) -o $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $<
